#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit

REGEX_ISSUE_ID="[a-zA-Z0-9,\.\_\-]+-[0-9]+"
BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
# $(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID") is standing for Jira ID
# for some reason it crashes when declared as a separate variable
if [[ -z "$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")" ]]; then
  echo $(cat "$1") > "$1"
else
  echo "[$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")]" $(cat "$1") > "$1"
fi
